# Configuração mínima para GitHub Pages
title: FFXIV Summoner Guide
email: meuphilim@gmail.com
description: >-
  Guia completo do Summoner em Final Fantasy XIV - Versão Dawntrail 7.2
baseurl: ""
url: "https://meuphilim.github.io/Guai-Arcanist-FF14/"

# Tema (opcional: use o padrão do GitHub ou remova para usar HTML puro)
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Markdown
markdown: GFM

# Exclusões
exclude:
  - Gemfile
  - Gemfile.lock
